sudo: false

language: c

os:
  - osx
  - linux

before_install:
  - rm -rf ~/.nvm && git clone --depth 1 https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - for i in {7..11}; do nvm i $i; done

install:
  - nvm use 11
  - npm i

script:
  - npm t

notifications:
  email: false
