version: 2
jobs:
  "gcc - static":
    docker:
      - image: ubuntu:16.04
        environment:
          CC: gcc
          CXX: g++
          SHARED_LIBS: OFF
          CTEST_OUTPUT_ON_FAILURE: 1
    steps:
      - checkout
      - run: apt-get update -qq
      - run: apt-get install -y software-properties-common
      - run: add-apt-repository ppa:ubuntu-toolchain-r/test
      - run: apt-get update -qq
      - run: >
          apt-get install -y --allow-unauthenticated
          build-essential
          cmake
          libmbedtls-dev
          ninja-build
      - run: ./.circleci/build_deps

workflows:
  version: 2
  build_and_test:
    jobs:
      - "gcc - static"
